### ISSUE TITLE
Encoding crash

### ISSUE THREAD

**Issue by G1ll0u** [jamesjohnmcguire/DigitalZenWorks.Email.ToolKit#20]
Hello, I'm using your tool that looks excellent but :

I run the command for a 12GB folder full of ELM in different folders and subfolders.
So I ran the command :
`Det.exe eml-to-pst C:\temp C:\temp2`
And here is what it returns :

```
[2024-10-15 12:48:38 INF] At: temp2::temp2/temp/Windows Live Mail/Windows Live Mail/Storage Folders/Dossier imp/Dossiers locaux/Information Adding outlook folder: Bookingcom
[2024-10-15 12:48:39 INF] At: temp2::temp2/temp/Windows Live Mail/Windows Live Mail/Storage Folders/Dossier imp/Dossiers locaux/Informatique Adding outlook folder: Kaspersky
[2024-10-15 12:48:41 INF] At: temp2::temp2/temp/Windows Live Mail/Windows Live Mail/Storage Folders/Dossier imp/Dossiers locaux/La Poste Adding outlook folder: EPost Office
[2024-10-15 12:48:41 ERR] System.ArgumentException: 'ISO8859_15' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at MsgKit.Mime.Decode.EncodingFinder.FindEncoding(String characterSet)
   at MsgKit.Mime.Decode.EncodedWord.Decode(String encodedWords)
   at MsgKit.Mime.Header.MessageHeader.ParseHeader(String headerName, String headerValue)
   at MsgKit.Mime.Header.MessageHeader.ParseHeaders(Dictionary`2 headers)
   at MsgKit.Converter.ConvertEmlToMsg(Stream emlFile, Stream msgFile)
   at MsgKit.Converter.ConvertEmlToMsg(String emlFileName, String msgFileName)
   at DigitalZenWorks.Email.ToolKit.Migrate.CopyEmlToPst(MAPIFolder mapiFolder, String emlFile)
   at DigitalZenWorks.Email.ToolKit.Migrate.CopyEmlFilesToPst(MAPIFolder pstFolder, IReadOnlyCollection`1 emlFiles)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlToPst(String path, String pstPath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Application.Program.EmlToPst(Command command)
   at DigitalZenWorks.Email.ToolKit.Application.Program.Main(String[] arguments)
Unhandled exception. System.ArgumentException: 'ISO8859_15' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at MsgKit.Mime.Decode.EncodingFinder.FindEncoding(String characterSet)
   at MsgKit.Mime.Decode.EncodedWord.Decode(String encodedWords)
   at MsgKit.Mime.Header.MessageHeader.ParseHeader(String headerName, String headerValue)
   at MsgKit.Mime.Header.MessageHeader.ParseHeaders(Dictionary`2 headers)
   at MsgKit.Converter.ConvertEmlToMsg(Stream emlFile, Stream msgFile)
   at MsgKit.Converter.ConvertEmlToMsg(String emlFileName, String msgFileName)
   at DigitalZenWorks.Email.ToolKit.Migrate.CopyEmlToPst(MAPIFolder mapiFolder, String emlFile)
   at DigitalZenWorks.Email.ToolKit.Migrate.CopyEmlFilesToPst(MAPIFolder pstFolder, IReadOnlyCollection`1 emlFiles)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlDirectoryToPst(MAPIFolder pstParent, String emlFolderFilePath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Migrate.EmlToPst(String path, String pstPath, Boolean adjust)
   at DigitalZenWorks.Email.ToolKit.Application.Program.EmlToPst(Command command)
   at DigitalZenWorks.Email.ToolKit.Application.Program.Main(String[] arguments)
   at DigitalZenWorks.Email.ToolKit.Application.Program.<Main>(String[] arguments)
```
It may be a corrupted EML. But I have 12GB of EMLs so I'm too lazy to find which one is broken...
Maybe your program should have something to ignore weird EMLs ?

Have a nice day !

**Comment by jamesjohnmcguire** [comment]
Hello there,

I've put in a fix to catch this error and then continue processing. 

Unfortunately, the EML file that causes this won't be properly processed, but the program will continue  with the remaining EML files.  To fix the actual encoding error in that EML file will take some work, with no guarantee of any success, as it will involve, among other things, working with other third-party libraries.

While I can't quite verify that this fix is correct, as I have never come across this before, I am very confident in the fix.  Please try and let me know the results.

I have also included the file name of the problematic EML file in the log, so you can follow up and investigate that file yourself.

It's all here in custom release just to fix this issue:
https://github.com/jamesjohnmcguire/DigitalZenWorks.Email.ToolKit/releases/tag/v1.10.59

Download, unzip, replace the binaries and please try again.

Would be nice if you could report the results, too!

**Comment by G1ll0u** [comment]
Yeah ! I have found which one was causing that and it worked ! I just
omitted the folder containing this file, I was so lazy...

My customer is gone, but I think I still have these EMLs. I'll try tomorrow
if I don't forget.


See you soon !

**Comment by G1ll0u** [comment]
It worked !
here's the log :
[report.txt](https://github.com/user-attachments/files/17414107/report.txt)

Thank you really much for this software !
